name: Check Run Timed Out Test

on:
  push:
  workflow_dispatch:

jobs:
  timed_out_job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Sleep longer than timeout
        run: |
          echo "This job will time out"
          sleep 300
