name: Deployment Status Test

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # used for pending state
    steps:
      - name: Deployment failure
        run: exit 1
